
platform:
  eurekaServerUrl : http://localhost:8761/eureka/

#服务端口
server:
  port: 8772
eureka:
  client:
    serviceUrl:
      defaultZone: ${platform.eurekaServerUrl}

spring:
  application:
    name: deer
