
platform:
  eurekaServerUrl : http://localhost:8761/eureka/

#服务端口
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${platform.eurekaServerUrl}

spring:
  application:
    name: ribbon
